export const USER_ROLES = {
  FORENSIC_AUDITOR: 'ROLE_FORENSIC_AUDITOR',
  PROCUREMENT_OFFICER: 'ROLE_PROCUREMENT_OFFICER',
  FINANCE_DIRECTOR: 'ROLE_FINANCE_DIRECTOR',
  VENDOR: 'ROLE_VENDOR'
};

export const ANOMALY_TYPES = {
  PRICE_SPIKE: 'PRICE_SPIKE',
  SPLIT_PO_STRUCTURING: 'SPLIT_PO_STRUCTURING',
  DUPLICATE_INVOICE: 'DUPLICATE_INVOICE',
  SHELL_VENDOR_NETWORK: 'SHELL_VENDOR_NETWORK',
  QUANTITY_GHOSTING: 'QUANTITY_GHOSTING',
  BENIGN_NORMAL: 'BENIGN_NORMAL'
};

export const AUDIT_STATUSES = {
  FLAGGED_CRITICAL: 'FLAGGED_CRITICAL',
  UNDER_INVESTIGATION: 'UNDER_INVESTIGATION',
  PAYMENT_FROZEN: 'PAYMENT_FROZEN',
  APPROVED: 'APPROVED',
  REJECTED_AUDIT: 'REJECTED_AUDIT'
};
